### ISSUE TITLE
Missing some permissions

### ISSUE THREAD

**Issue by bellegarde-c** [flathub/io.gitlab.azymohliad.WatchMate#3]
[Capture vidéo du 2023-02-20 18-08-21.webm](https://user-images.githubusercontent.com/57196916/220166861-7176342f-c3a3-4c98-974f-3458556086f8.webm)

**Comment by azymohliad** [comment]
Yeah, this is a known issue, but your report is another evidence that I need to address this ASAP. You can find more details [here](https://github.com/azymohliad/watchmate/issues/6)

**Comment by azymohliad** [comment]
Just published v0.4.2 with less confusing pop-up message with a link to the issue, should be available on flathub in a few hours

**Comment by azymohliad** [comment]
Hey, since this is partially addressed and is tracked in another issue linked above, I'm closing this as a duplicate just to keep it clean. I hope you don't mind.

Btw, very offtopic, but it's the easiest to share it with you here. You've reported [the timezone issue on PostmarketOS](https://gitlab.com/azymohliad/watchmate/-/issues/11) before. There are some discoveries [here](https://togithub.com/azymohliad/watchmate/issues/22#issuecomment-1511716820) that you might be interested in (it's likely the same issue). The TL;DR is that it's likely an issue between Flatpak and Alpine timezone handling. Alpine might set `/etc/localtime` to link to `/etc/zoneinfo/...`, and Flatpak recreates `/etc/localtime` symlink in the container by the timezone name, but to extract the timezone name it doesn't lookup in `/etc/zoneinfo` by default. Probably the best workaround until this is properly fixed upstream is to export `TZDIR=/etc/zoneinfo` systemwide.
